const localhost_urls = {
    LOCALHOST_URL: 'http://localhost:8001',
    GET_ALL_PRODUCTS_PATH: '/all-products',
    GET_ALL_PRODUCTS_PATH_FULL: 'http://localhost:8001/all-products',
    GET_PRODUCT_BY_ID_PATH: '/product?pid=<$pid>',
    GET_PRODUCT_BY_ID_PATH_FULL: 'http://localhost:8001/product?pid=<$pid>',
    GET_COUNT_SUB_BY_PID_PATH: '/subproduct/count-by-productid?pid=<$pid>',
    GET_COUNT_SUB_BY_PID_FULL_PATH: 'http://localhost:8001/subproduct/count-by-productid?pid=<$pid>',
    GET_ALL_SUB_BY_PID_PATH: '/subproduct/get-by-productid?pid=<$pid>',
    GET_ALL_SUB_BY_PID_FULL_PATH: 'http://localhost:8001/subproduct/get-by-productid?pid=<$pid>',
    CREATE_PRODUCT_PATH: '/product/',
    CREATE_PRODUCT_FULL_PATH: 'http://localhost:8001/product/',
    EDIT_PRODUCT_PATH: '/product/',
    EDIT_PRODUCT_FULL_PATH: 'http://localhost:8001/product/',
    CREATE_SUBPRODUCT_PATH: '/sub-product/',
    CREATE_SUBPRODUCT_FULL_PATH: 'http://localhost:8001/sub-product/',
    EDIT_SUBPRODUCT_PATH: '/sub-product/',
    EDIT_SUBPRODUCT_FULL_PATH: 'http://localhost:8001/sub-product/',
    DELETE_SUBPRODUCT_BY_SID_PATH: '/subproduct/remove-by-sid?sid=<$sid>',
    DELETE_SUBPRODUCT_BY_SID_FULL_PATH: 'http://localhost:8001/subproduct/remove-by-sid?sid=<$sid>',
    DELETE_SUBPRODUCT_BY_PID_PATH: '/subproduct/remove-by-pid?pid=<$pid>',
    DELETE_SUBPRODUCT_BY_PID_FULL_PATH: 'http://localhost:8001/subproduct/remove-by-pid?pid=<$pid>',
    DELETE_PRODUCT_BY_PID_PATH: '/product/remove-by-pid?pid=<$pid>',
    DELETE_PRODUCT_BY_PID_FULL_PATH: 'http://localhost:8001/product/remove-by-pid?pid=<$pid>',
}
localhost_urls

const localhost_ip_urls = {
    LOCALHOST_URL: 'http://192.168.1.21:8001',
    GET_ALL_PRODUCTS_PATH: '/all-products',
    GET_ALL_PRODUCTS_PATH_FULL: 'http://192.168.1.21:8001/all-products',
    GET_HOME_PRODUCTS_PATH: '/home-products',
    GET_HOME_PRODUCTS_PATH_FULL: 'http://192.168.1.21:8001/home-products',
    GET_PRODUCT_BY_ID_PATH: '/product?pid=<$pid>',
    GET_PRODUCT_BY_ID_PATH_FULL: 'http://192.168.1.21:8001/product?pid=<$pid>',
    GET_COUNT_SUB_BY_PID_PATH: '/subproduct/count-by-productid?pid=<$pid>',
    GET_COUNT_SUB_BY_PID_FULL_PATH: 'http://192.168.1.21:8001/subproduct/count-by-productid?pid=<$pid>',
    GET_ALL_SUB_BY_PID_PATH: '/subproduct/get-by-productid?pid=<$pid>',
    GET_ALL_SUB_BY_PID_FULL_PATH: 'http://192.168.1.21:8001/subproduct/get-by-productid?pid=<$pid>',
    CREATE_PRODUCT_PATH: '/product/',
    CREATE_PRODUCT_FULL_PATH: 'http://192.168.1.21:8001/product/',
    EDIT_PRODUCT_PATH: '/product/',
    EDIT_PRODUCT_FULL_PATH: 'http://192.168.1.21:8001/product/',
    CREATE_SUBPRODUCT_PATH: '/sub-product/',
    CREATE_SUBPRODUCT_FULL_PATH: 'http://192.168.1.21:8001/sub-product/',
    EDIT_SUBPRODUCT_PATH: '/sub-product/',
    EDIT_SUBPRODUCT_FULL_PATH: 'http://192.168.1.21:8001/sub-product/',
    DELETE_SUBPRODUCT_BY_SID_PATH: '/subproduct/remove-by-sid?sid=<$sid>',
    DELETE_SUBPRODUCT_BY_SID_FULL_PATH: 'http://192.168.1.21:8001/subproduct/remove-by-sid?sid=<$sid>',
    DELETE_SUBPRODUCT_BY_PID_PATH: '/subproduct/remove-by-pid?pid=<$pid>',
    DELETE_SUBPRODUCT_BY_PID_FULL_PATH: 'http://192.168.1.21:8001/subproduct/remove-by-pid?pid=<$pid>',
    DELETE_PRODUCT_BY_PID_PATH: '/product/remove-by-pid?pid=<$pid>',
    DELETE_PRODUCT_BY_PID_FULL_PATH: 'http://192.168.1.21:8001/product/remove-by-pid?pid=<$pid>',

    CREATE_FAQ_PATH: '/faq/',
    CREATE_FAQ_FULL_PATH: 'http://192.168.1.21:8001/faq/',
    EDIT_FAQ_PATH: '/faq/',
    EDIT_FAQ_FULL_PATH: 'http://192.168.1.21:8001/faq/',
    GET_ALL_FAQS_PATH: '/all-faqs',
    GET_ALL_FAQS_PATH_FULL: 'http://192.168.1.21:8001/all-faqs',
    SEARCH_FAQS_PATH: '/search-faq?keyword=<$keyword>',
    SEARCH_FAQS_PATH_FULL: 'http://192.168.1.21:8001/search-faq?keyword=<$keyword>',
    GET_FAQ_BY_FID_PATH: '/faq?fid=<$fid>',
    GET_FAQ_BY_FID_FULL_PATH: 'http://192.168.1.21:8001/faq?fid=<$fid>',
    DELETE_FAQ_BY_FID_PATH: '/faq?fid=<$fid>',
    DELETE_FAQ_BY_FID_FULL_PATH: 'http://192.168.1.21:8001/faq?fid=<$fid>',

    CREATE_BLOG_PATH: '/blog/',
    CREATE_BLOG_FULL_PATH: 'http://192.168.1.21:8001/blog/',
    EDIT_BLOG_PATH: '/blog/',
    EDIT_BLOG_FULL_PATH: 'http://192.168.1.21:8001/blog/',
    GET_ALL_BLOGS_PATH: '/all-blogs',
    GET_ALL_BLOGS_PATH_FULL: 'http://192.168.1.21:8001/all-blogs',
    GET_HOME_BLOGS_PATH: '/home-blogs',
    GET_HOME_BLOGS_PATH_FULL: 'http://192.168.1.21:8001/home-blogs',
    GET_BLOG_BY_BID_PATH: '/blog?bid=<$bid>',
    GET_BLOG_BY_BID_FULL_PATH: 'http://192.168.1.21:8001/blog?bid=<$bid>',
    DELETE_BLOG_BY_BID_PATH: '/blog?bid=<$bid>',
    DELETE_BLOG_BY_BID_FULL_PATH: 'http://192.168.1.21:8001/blog?bid=<$bid>',

    LOGIN_PATH: '/login/',
    LOGIN_FULL_PATH: 'http://192.168.1.21:8001/login/',
    VERITY_TOKEN_PATH: '/verity-token/',
    VERITY_TOKEN_FULL_PATH: 'http://192.168.1.21:8001/verity-token/',
}

const header = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PATCH, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Origin, Content-Type, X-Auth-Token",
    "Content-Type": "text/json",
}

const firebaseGS = 'gs://abaso-dev.appspot.com/'

module.exports = {
    urls: localhost_ip_urls,
    header: header,
    firebaseGS: firebaseGS
}